name: ElysiumCore
version: '1.0-SNAPSHOT'
main: de.satsuya.elysiumCore.ElysiumCore
api-version: '1.21'

commands:
  test:
    description: Test command for ElysiumCore
    usage: /test
  lootchest:
    description: Main command for managing loot chests.
    usage: /<command> [create|edit|give]
    permission: elysiumcore.admin.lootbox
    permission-message: You do not have permission to use this command.
  reloadcore:
    description: Reloads the ElysiumCore configuration.
    usage: /reloadcore
    permission: elysiumcore.admin.reload
    permission-message: You do not have permission to reload the core.