name: ElysiumCore
version: '1.0-SNAPSHOT'
main: de.satsuya.elysiumCore.ElysiumCore
api-version: '1.21'

commands:
  test:
    description: Test command for ElysiumCore
    usage: /test
  inventory:
    description: All items from ElysiumCore
    usage: /inventory
    permission: elysiumcore.admin.inventory
  reloadcore:
    description: Reloads the ElysiumCore configuration.
    usage: /reloadcore
    permission: elysiumcore.admin.reload
    permission-message: You do not have permission to reload the core.


permissions:
  elysiumcore.admin.reload:
    description: Allows reloading the ElysiumCore configuration.
    default: op
  elysiumcore.lootbox.open:
    description: Allows players to open lootboxes.
    default: true
  elysiumcore.admin.inventory:
    description: Allows to open the inventory of Elysium
    default: op
