name: ElysiumCore
version: '1.0-SNAPSHOT'
main: de.satsuya.elysiumCore.ElysiumCore
api-version: '1.21'
depend: [LuckPerms]
softdepend: [ProtocolLib]


commands:
  test:
    description: Test command for ElysiumCore
    usage: /test
  inventory:
    description: All items from ElysiumCore
    usage: /inventory
    permission: elysiumcore.admin.inventory
  reloadcore:
    description: Reloads the ElysiumCore configuration.
    usage: /reloadcore
    permission: elysiumcore.admin.reload
    permission-message: You do not have permission to reload the core.
  guild:
    description: Die Haupt-Gildenbefehle.
    usage: /guild <create|invite|join|leave|kick|list|clearinvites|delete>
    permission: elysiumcore.guild
    aliases:
      - g
      - guilden
  eco:
    description: Economy Commands
    usage: /eco <balance|pay>
    permission: elysiumcore.eco
    aliases:
      - e
      - money
  reboot:
    description: Reboots the server
    usage: /reboot
    permission: elysiumcore.admin.reboot
  gm:
    description: Call a gamemaster
    usage: /gm
    permission: elysiumcore.gm
  report:
    description: Report a player or a bug
    permission: elysiumcore.report
  speed:
    description: changes the speed of the command sender
    permission: elysiumcore.speed
  vanish:
    description: makes a player invisable for others
    permission: elysiumcore.vanish
  ah:
    description: Öffnet das Auktionshaus
    usage: /ah
    permission: elysiumcore.ah


permissions:
  elysiumcore.admin.reload:
    description: Allows reloading the ElysiumCore configuration.
    default: op
  elysiumcore.admin.inventory:
    description: Allows to open the inventory of Elysium
    default: op
  elysiumcore.guild:
    description: Allows players to use the guild command.
    default: true
  elysiumcore.eco:
    description: Allows players to use the eco command.
    default: true
  elysiumcore.admin.eco:
    description: Allows players to use the eco admin command.
    default: op
  elysiumcore.admin.reboot:
    description: reboot permission
    default: op
  elysiumcore.gm.notify:
    description: notify player on gm command
    default: op
  elysiumcore.gm:
    description: allow use of gm command
    default: true
  elysiumcore.report:
    description: allow use of report command
    default: true
  elysiumcore.report.notify:
    description: notify player on report
    default: op
  elysiumcore.speed:
    description: allow use of speed command
    default: op
  elysiumcore.chat.spy:
    description: spy on the chat event
    default: op
  elysiumcore.vanish:
    description: allow use of vanish command
    default: op
  elysiumcore.vanish.see:
    description: allows see vanished players
    default: op
  elysiumcore.vanish.other:
    description: allows command vanish on other players
    default: op
  elysiumcore.ah:
    description: allows use of ah command
    default: true